# Generated by Django 5.2.12 on 2026-03-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('scada', 'SCADA System'), ('dcs', 'Distributed Control System'), ('plc', 'Programmable Logic Controller'), ('network', 'Network Infrastructure'), ('server', 'Server'), ('workstation', 'Workstation'), ('safety', 'Safety System')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mitigated', 'Mitigated'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('attack_vector', models.CharField(max_length=100)),
                ('potential_impact', models.TextField()),
                ('likelihood_score', models.FloatField(default=0.0)),
                ('impact_score', models.FloatField(default=0.0)),
                ('detected_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_assets', models.ManyToManyField(to='threats.plantasset')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='threats.threatcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cve_id', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('cvss_score', models.FloatField(default=0.0)),
                ('is_patched', models.BooleanField(default=False)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.plantasset')),
            ],
        ),
    ]
