# Generated by Django 5.2.12 on 2026-03-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAMAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('confidentiality_score', models.FloatField(default=0.0)),
                ('integrity_score', models.FloatField(default=0.0)),
                ('availability_score', models.FloatField(default=0.0)),
                ('threat_likelihood', models.FloatField(default=0.0)),
                ('vulnerability_factor', models.FloatField(default=0.0)),
                ('control_effectiveness', models.FloatField(default=0.0)),
                ('overall_risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('assessed_by', models.CharField(max_length=100)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.plantasset')),
            ],
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('impact', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('risk_score', models.FloatField()),
                ('mitigation_notes', models.TextField(blank=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threat')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment.tamassessment')),
            ],
        ),
    ]
