# Generated by Django 5.2.12 on 2026-03-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security_controls', '0001_initial'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('critical', 'Critical Priority'), ('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=20)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personnel_assigned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.plantasset')),
                ('assigned_controls', models.ManyToManyField(blank=True, to='security_controls.securitycontrol')),
            ],
        ),
    ]
