name: Auto Label PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add default labels
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.addLabels({
              issue_number: prNumber,
              owner: owner,
              repo: repo,
              labels: ["project-submitted", "project-under-review"]
            });
